[NUI] Add GlWindow
Samsung/TizenFX pull request #1945
Opened 2020-08-25 12:14 UTC by dkdk-ryu

GlWindow allows you to render scenes with OpenGL ES.

### Description of Change ###

### API Changes ###

 - ACR:

2020-08-25 23:19 UTC, hyunjushin commented
please share GlWindow sample application code.

2020-08-26 00:01 UTC, sparrow74 commented on src/Tizen.NUI/src/public/GlWindow.cs
> +        public void RegisterGlCallback( GlInitializeType glInit, GlRenderFrameType glRenderFrame, GlTerminateType glTerminate )
Modify this function to use local value. please.
Refer my repository of GLWindow_v1.

2020-08-26 00:01 UTC, sparrow74 commented on src/Tizen.NUI/src/public/GlWindowEvent.cs
> +    public partial class GlWindow
Please, add [EditorBrowsable(EditorBrowsableState.Never)].

2020-08-26 00:40 UTC, hyunjushin approved these changes

2020-08-26 00:43 UTC, hyunjushin requested changes
check warning messages

2020-08-27 04:23 UTC, WonyoungChoi commented
I think `GL` prefix is better than `Gl`.  It is generally used in capital letters as a proper noun.

2020-08-27 04:25 UTC, idkiller commented
When implementing property getter / setter or add / remove of event, you can see code that initializes by null check in most situations.
If you use Lazy<T>, you can keep the code more concise and nice, so it would be nice to consider using it.

2020-08-28 07:21 UTC, dongsug-song commented on src/Tizen.NUI/src/public/GlWindow.cs
> +            init2 = new HandleRef(this, Marshal.GetFunctionPointerForDelegate<Delegate>(init1));
could you do naming the values as meaningful one?
also could you check this link?

https://docs.microsoft.com/ko-kr/dotnet/api/system.gc.keepalive?view=netcore-3.1

if these variables are for blocking garbage collected, then you can use KeepAlive maybe...

2020-08-28 07:21 UTC, dongsug-song commented on src/Tizen.NUI/src/public/GlWindowEvent.cs
> +        private event EventHandler<VisibilityChangedArgs> VisibilityChangedEventHandler;
this is trivial one. but could you decide whether underscore( _ ) is used for private variable or not?
some has underscore but this one doesn't have it... ^^;

2020-09-02 01:56 UTC, dkdk-ryu commented
> I think `GL` prefix is better than `Gl`. It is generally used in capital letters as a proper noun.

I changed them.

2020-09-03 03:03 UTC, dongsug-song commented
@hyunjushin 
@idkiller 

Hello, 
Actually, this patch needs be merged urgently. 
(and these API are all hidden API)
I talked with Mr. dkdk-ryu and we will do refactoring later soon.
(about using Lazy<T>, handling exceptions and etc...)
so for now, I want you to accept this to be merged.
Thank you.

2020-09-03 03:03 UTC, dongsug-song approved these changes

2020-09-03 03:19 UTC, hyunjushin approved these changes

2020-09-03 06:19 UTC, merged