[Bluetooth][Non-ACR] Add the exception handling logic
Samsung/TizenFX pull request #2021
Opened 2020-09-17 04:28 UTC by Wootak

Signed-off-by: Wootak Jung <wootak.jung@samsung.com>

2020-09-17 07:52 UTC, dh79pyun approved these changes
Verified that the issue is resolved with this patchset
https://code.sec.samsung.net/jira/browse/TSIX-6272

2020-09-17 08:25 UTC, myroot requested changes
`BluetoothHidDeviceImpl`, `BluetoothHidImpl`, `BluetoothOppClientImpl`, `BluetoothAvrcpImpl` are missing

Please update all subclass of BluetoothProfile

2020-09-18 04:02 UTC, Wootak commented
Updated.

2020-09-18 05:30 UTC, myroot approved these changes

2020-09-18 05:39 UTC, merged