Tizen.Peripheral move all classes to it's namespaces.
Samsung/TizenFX pull request #2033
Opened 2020-09-21 06:54 UTC by xerrni

Signed-off-by: Ernest Borowski <e.borowski@samsung.com>

### Description of Change ###
Move all classes to it's own namespaces.

### API Changes ###

Move class:
1.
```csharp
  public class Tizen.Peripheral.I2c (class):
        public I2c(int bus, int address) (constructor);
        public void Close() (method);
        public void Read(byte[] dataOut) (method);
        public void Write(byte[] data) (method);
        public byte ReadRegisterByte(byte register) (method);
        public void WriteRegisterByte(byte register, byte data) (method);
        public ushort ReadRegisterWord(byte register) (method);
        public void WriteRegisterWord(byte register, ushort data) (method);
        public void Dispose() (method);
```
to `Tizen.Peripheral.I2c` namespace
2. 
```csharp
    public class Tizen.Peripheral.Adc : IDisposable (class):
        public Adc(int device, int channel) (constructor);
        public uint ReadValue() (method);
        public void Close() (method);
        public void Dispose() (method);
```
to `Tizen.Peripheral.Adc` namespace

2020-09-21 10:50 UTC, myroot requested changes
❌ DO NOT use the same name for a namespace and a type in that namespace.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces

I recommend to change class name like below (it comes from MS API)
Adc -> AdcChannel 
Gpio -> GpioPin 
I2c -> I2cDevice 
Spi -> SpiDevice 
Pwm -> PwmPin 
Uart -> SerialPort

2020-09-21 22:48 UTC, WonyoungChoi commented
How about moving all classes under `Tizen.Peripherals` namespace?

2020-09-23 08:20 UTC, xerrni commented
> 
> 
> ❌ DO NOT use the same name for a namespace and a type in that namespace.
> https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces
> 
> I recommend to change class name like below (it comes from MS API)
> Adc -> AdcChannel
> Gpio -> GpioPin
> I2c -> I2cDevice
> Spi -> SpiDevice
> Pwm -> PwmPin
> Uart -> SerialPort

done

2020-09-23 08:21 UTC, xerrni commented
> 
> 
> How about moving all classes to under `Tizen.Peripherals` namespace?

I would like to keep Tizen.Peripheral name so it will be consistent with native API.

2020-09-23 08:37 UTC, myroot approved these changes

2020-09-25 07:40 UTC, xerrni commented
I have rebased this commit.

2020-09-28 01:49 UTC, merged