[Tts/Stt] Use thread lock only when add and remove event handler
Samsung/TizenFX pull request #2782
Opened 2021-03-24 01:25 UTC by stom-hwang

### Description of Change ###
This patch creates the thread lock for event handlers and removes other useless thread locks.

### API Changes ###

 - No ACR

2021-03-24 06:18 UTC, myroot requested changes

2021-03-24 06:18 UTC, myroot commented on src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
> +                                }
No need lock here, `_recognitionResult?.`  it guarantee thread safe
```suggestion
                                _recognitionResult?.Invoke(this, args);
```

2021-03-24 06:18 UTC, myroot commented on src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
> +                            }
No need lock here
```suggestion
                            _stateChanged?.Invoke(obj, args);
```

2021-03-24 06:18 UTC, myroot commented on src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
> +                            }
No need lock here
```suggestion
                            _errorOccurred?.Invoke(this, args);
```

2021-03-24 06:18 UTC, myroot commented on src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
> +                            }
No need lock here
```suggestion
                            _defaultLanguageChanged?.Invoke(this, args);
```

2021-03-24 06:18 UTC, myroot commented on src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
> +                            }
No need lock

2021-03-24 07:04 UTC, stom-hwang commented
Thank you to share the information.
I will remove the thread lock from delegator invocation.

2021-03-24 22:18 UTC, myroot approved these changes

2021-03-25 01:50 UTC, urmain approved these changes
LGTM

2021-03-25 01:51 UTC, merged

2021-03-25 01:52 UTC, syeonholic approved these changes
It looks good to me.