[NUI] Add focusableInTouchMode property
Samsung/TizenFX pull request #3154
Opened 2021-06-04 03:17 UTC by JoogabYun

This is a property that allows you to have focus even when touched.

If Focusable is false, FocusableInTouchMode is disabled.
If you want to have focus on touch in touch mode, you need to set both settings to true.

focusable = true,
focusableInTouchMode = true,

### Description of Change ###

### API Changes ###

 - ACR:

2021-06-04 03:52 UTC, myroot requested changes

2021-06-04 03:52 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
> +        internal void SetTouchFocusable(bool focusable)
How about change name for the consistency like below
```suggestion
        internal void SetFocusInTouchMode(bool enabled)
```

2021-06-04 03:52 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
> +        internal bool IsTouchFocusable()
```suggestion
        internal bool IsFocusInTouchMode()
```

2021-06-04 03:52 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
> +        internal bool FocusInTouchModeState
You don't need this internal property

2021-06-04 03:52 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
> +            defaultValueCreator: (bindable) => ((ViewStyle)bindable).focusableInTouchMode
I think, default value should be null, because it is nullable value, remove `defaultValueCreator`

2021-06-04 03:52 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
> +            propertyChanged: (bindable, oldValue, newValue) => ((ViewStyle)bindable).focusableInTouchMode = (bool?)newValue,
You need to check null becuase it is nullable value

2021-06-07 01:52 UTC, myroot approved these changes

2021-06-08 00:33 UTC, huiyueun approved these changes
LGTM

2021-06-16 01:21 UTC, dkdk-ryu commented
LGTM

2021-06-16 01:24 UTC, merged