[NUI] VectorGraphics: Add Gradient feature
Samsung/TizenFX pull request #3389
Opened 2021-08-06 08:34 UTC by JSUYA

### Description of Change ###

Add Gradient, LinearGradient, and RadialGradient classes that
implement Linear and Radial Gradient features.
Each Gradient can be applied to Fill and Stroke of Shape after
setting Bounds and ColorStop suitable for style.

### API Changes ###

 - ACR:no

dependency patch : 
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-adaptor/+/261217/
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/262262/

2021-08-09 02:53 UTC, huiyueun approved these changes
LGTM

2021-08-09 03:19 UTC, dongsug-song commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +        public ColorStop(float offset, Color color)
안녕하세요.
`ColorStop` 클래스 전체를 hidden-api 로 만드는것을 의도 하셨다면, 프로퍼티와 메소드에도 `[EditorBrowsable(EditorBrowsableState.Never)]` 를 붙여 주시기 바랍니다.

2021-08-09 03:22 UTC, dongsug-song commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +        public Color Color
안녕하세요.
우선 https://code.sec.samsung.net/jira/browse/GRE-2025 를 먼저 확인 부탁드립니다.
프로퍼티의 타입을 클래스로 쓰는것은 많은 문제가 발생할 수 있어서 지양하고 있습니다.
`SetColor(Color color)` 같은 메소드로 바꾸는것은 어떨까요?

2021-08-09 03:24 UTC, dongsug-song commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +            set {
안녕하세요. 
`{` 가 다음줄로 가는것이 읽기에 좋을것 같습니다.
"ctrl+k+d" or "ctrl+k+f" 를 사용해서 자동으로 포멧을 맞춰주실수 있습니다.

- Visual Studio in Windows : https://stackoverflow.com/questions/1435691/visual-studio-format-entire-file

- VS Code in Ubuntu : https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode

2021-08-10 02:06 UTC, huiyueun commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +        public Color Color
아래 패치로 Color의 Setter는 Deprecated 시켰기 때문에 프로퍼티 형태로 지원해도 괜찮지 않을까요?
https://github.com/samsung/TizenFX/pull/2894

다른 프로퍼티와 같은 사용성 제공성이나 XAML에서의 사용을 생각하면 지금과 같은 사용이 괜찮을 것 같아 보입니다.

2021-08-11 08:11 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +        public ColorStop(float offset, Color color)
누락되었었네요 추가 했습니다. 감사합니다.

2021-08-11 08:12 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +            set {
수정했습니다

2021-08-11 09:47 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +        public Color Color
우선 오해가 있는 부분이 있어서, 의견드리고 싶습니다. Property로서 제공하는 타입이 클래스이어서 문제가 되는것은 아닙니다.
값으로서 표현되어야 하는 자료형이 클래스 타입으로 표현되기 때문에 문제가 되는것입니다.

따라서, SetColor/GetColor보다는 Color Property가 더 적합합니다.

그리고 GetColor/SetColor에서도 현재 Color Property에서 발생하는 문제점이 동일하게 발생됩니다.

즉, 
``` c#
 var color = new Color(...);
 obj1.SetColor(color);
 obj2.SetColor(color);
 obj2.GetColor().R = 1;
```
이렇게 하는 경우 의도와 다르게 obj1의 Color로 바뀌게 됩니다.

그래서, 클래스라고 해서 Property로 하지 않고 get/set 메소드로 변경하는것은 적용하지 않고 그대로 Property 두었으면 합니다.

2021-08-13 01:09 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +        public Color Color
> @dongsug-song , @JSUYA , @huiyueun
> 우선 오해가 있는 부분이 있어서, 의견드리고 싶습니다. Property로서 제공하는 타입이 클래스이어서 문제가 되는것은 아닙니다.
> 값으로서 표현되어야 하는 자료형이 클래스 타입으로 표현되기 때문에 문제가 되는것입니다.
> 
> 따라서, SetColor/GetColor보다는 Color Property가 더 적합합니다.
> 
> 그리고 GetColor/SetColor에서도 현재 Color Property에서 발생하는 문제점이 동일하게 발생됩니다.
> 
> 즉,
> 
> ```cs
>  var color = new Color(...);
>  obj1.SetColor(color);
>  obj2.SetColor(color);
>  obj2.GetColor().R = 1;
> ```
> 
> 이렇게 하는 경우 의도와 다르게 obj1의 Color로 바뀌게 됩니다.
> 
> 그래서, 클래스라고 해서 Property로 제공하는 것을 지양하고 메소드로 제공하도로 수정하지 말고, 그대로 Property로 제공하였으면 합니다.

이 부분에 대해서 다른 부분에서도 Set/Get 함수를 사용한 부분이 있어서 property로 변경하는 패치를 별도로 만들도록 하겠습니다.

2021-08-13 01:16 UTC, dongsug-song commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
> +        public Color Color
@myroot 님, @huiyueun 님
안녕하세요.
네. 제가 완전 잘못 리뷰를 드렸네요. 
클래스 타입 프로퍼티 사용을 지양하고 메소드를 쓰도록 하는 것은 잘못된 리뷰 입니다.
불편을 드려서 죄송하고, 올바른 리뷰 감사드립니다.

@JSUYA 님
메신져로 말씀드렸다시피, setter 를 deprecated 했고 setting 은 생성자를 사용하도록 했으므로, 클래스 타입의 프로퍼티를 사용하도록 다시 패치를 올려 주셨으면 합니다. (메소드 제거)

2021-08-13 01:18 UTC, dongsug-song requested changes
메신져로 말씀드렸다시피, setter 를 deprecated 했고 setting 은 생성자를 사용하도록 했으므로, 클래스 타입의 프로퍼티를 사용하도록 다시 패치를 올려 주셨으면 합니다. (메소드 제거)

2021-08-13 07:24 UTC, dongsug-song approved these changes

2021-08-13 07:24 UTC, merged