[NUI] VectorGraphics: Add Shape.AddPath API
Samsung/TizenFX pull request #3423
Opened 2021-08-13 08:48 UTC by JSUYA

### Description of Change ###

Adds an API that adds a large path information.
The PathCommands has a PathCommandType array, a Point array
and the number of each array.

### API Changes ###

 - ACR:no

dependency patch
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/262530/

2021-08-13 10:13 UTC, myroot requested changes

2021-08-13 10:13 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
xxxCount 인자를 필요 없는것 같습니다.
배열 대신, `IEnumerable<PathCommandType>`을 사용하는것이 가능하다면 그걸로 변경해주세요

2021-08-13 10:13 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public enum PathCommandType
nested type은 사용하지 않은것이 일반적인 룰입니다.

❌ DO NOT use public nested types as a logical grouping construct; use namespaces for this.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types

2021-08-13 10:13 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
❌ DO NOT use ArrayList or List<T> in public APIs.

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections

2021-08-13 10:44 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
PathCommentType과 point가 결합된것이 일반적으로 표현되는 PathComment로 보입니다.따라서 이둘을 하나의 타입으로 묶는게 코드 가독성이나 사용성에서 나아 보입니다.

2021-08-13 14:07 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
이 함수는 패스 정보를 command type(move, line, cubic, close)과 각 타입의 float type 배열을 자료의 복사나 별도의 컨테이너 없이 Shape에 추가하기 위해 만들었습니다. 

해당 배열들은 dali를 거쳐 thorvg 의 객체에서 그대로 복사가 됩니다. 패스 데이터가 버퍼 형태로 아주 많은 경우를 지원하기 위해 준비된 API입니다. (AddPath의 docs에 note 내용 참조)

넣은 commands를 사용자가 별도로 조회하거나 일부를 수정하는 형태의 사용성을 제공하려는 것은 아닙니다. dali 쪽에서도 이런 부분을 고려해 배열을 그대로 넘길 수 있게 처리 했습니다. 별도의 컨테이너가 사용된다면 이런 API를 사용할 필요 없이 사용자 쪽에서 AddMoveTo(), AddLineTo()를 각각 알아서 호출 하면 되기 때문에 이 API를 제공할 필요가 없습니다.

2021-08-14 02:26 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
그런 목적이라면, SVG path command를 string으로 바로 입력으로 넣는것이 더 낫지 않을까 합니다.
우선 대부분의 백터 패스데이터가 지금 작성하신 형태로 갖춰져 있지 않을것이고, SVG Path command형태로 있는것을 PathCommandType과 Points로 변환해서 입력할 것인데 , 당장 아래 추가된 예제만 보더라도 특정 points가 어떤 command를 위한 points인지 바로 확인이 어렵기 때문에 path가 원하는데로 그려지지 않은 상황에서 디버깅이 매우 어려울것 같습니다.

그리고 많은 백터 그래픽 라이브러리에서 이미 SVG path command를 그대로 입력으로 사용하기도 있기 때문에, 사용자 입장에서도 더 원하는 방법이 아닐까 합니다.
https://docs.microsoft.com/ko-kr/xamarin/xamarin-forms/user-interface/graphics/skiasharp/curves/path-data

2021-08-14 05:59 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
SVG Path를 전달하는 건 다른 문제입니다. 이 기능을 지원하려면 별도의 인터페이스가 되어야 합니다. 
이 인터페이스와는 무관한 내용으로 보입니다.
SVG Path를 자체적으로 해석해 이 기능을 쓸 수 있다 뿐이지 SVG Path를 해석해서 붙이는데 도움이 되고자 이러한 형태가 필요한것은 아닙니다. SVG Path에 대한 요청은 별도로 다루어 져야 합니다.

보내주신 skia sharp 링크의 원호를 그리는 3가지 방법의 예제를 보면 탄젠트 호를 그리는 방식에서 ArcTo를 loop를 통해 연속적으로 부르고 있습니다. 폴리곤의 형태가 더 크고 복잡할 수록(외각선을 그려야 한다던지.. 로봇 청소기가 맵을 그린다던지 등등) 호출하는 양이 많아 집니다. (내부적으로는 결국 이 인터페이스에서 제공하는 type과 float point를 저장 하는 동작은 동일 합니다.) 그러므로 사용자가 어떤 컨테이너를 통해서 type과 point 정보를 쌓던 전달은 배열 형태로만 전달이 되면 한번의 호출로 처리를 할 수 있습니다.

디버깅의 경우에도 디버깅이 필요한 수준의 Path를 쌓는 상황이라면 사용자가 직접 쌓는 컨테이너에만 잘 쌓여 있고 사용자가 그 컨테이너를 확인하면 되는것이지 버퍼로 전달 된 이후 부터의 동작은 API를 제공하는 입장의 디버깅이고 동작 보장이 되면 되는 것이기 때문에 원하는 `path가 원하는데로 그려지지 않은 상황에서 디버깅`과 이 인터페이스와는 무관한것 같습니다.

이 인터페이스가 제공하고자 하는 방식이 NUI 인터페이스에서 허용되지 않는 문법(docs에서 사용성에 대한 고지를 한 상태에서)이라면 해당 API를 제공하지 않고 기존의 AddXXXX method를 연속 호출 하는 형태로 가이드가 되면 될 것 같습니다.

2021-08-14 06:06 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
말씀 하신 SVG Path를 string 형태로 등록하는 부분에 대해서 논의하도록 하겠습니다.
https://github.com/Samsung/thorvg/issues/717

2021-08-14 06:35 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
>이 함수는 패스 정보를 command type(move, line, cubic, close)과 각 타입의 float type 배열을 자료의 복사나 별도의 컨테이너 없이 Shape에 추가하기 위해 만들었습니다.

이 의미가 무엇일까요? 우선 파라메터 타입을 IEnumerable을 사용한다고 해서 배열 타입을 입력으로 넣지 못하는것이 아닙니다.
그리고 Path 정보라는게 원천적으로 날것으로 PathCommand타입과 Points로 각각 존재하지도 않는 것이고, 타이핑하거나 코드로 변환해서  넣어야할 코드인데, 이상 지금과 같이 배열로 각각 나열하는것과 한 객체에 담아서 배열로 담아 넣는것과의 차이가 무엇일까요?
 한 객체에 담아서 보내면 안되는 이유가  무엇일까요?

지금 추가하는 API의 목적은 제가 파악한 바로는 여러번의 API호출 없이 대량의 데이터를 한번에 입력하기 위함으로 보이는데요
이 모든것이 제가 리뷰했던, 배열을 사용하지 않는것, Command타입과 Point를 묶는것 둘다 목적을 달성하는데 문제가 안된다고 판단되는데 제가 모르는 다른 문제가 있는것 일까요?

혹시나 이 API의 의도가  "사용자가 전달한 자료형을 Native API로 전달하기 위해 **변환하는 과정을 거치지 않기** 위함"이라는 의도일까요?

2021-08-14 07:39 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
네 변환하는 과정을 거치지 않기 위함입니다.
초기에 Dali에서도 Dali에서 권장하는 형태로 리스트 컨테이너에 넣은 뒤 thorvg에 전달하기 전 배열 형태로 다시 변환하여 전달하는 형태로 구현을 했었는데 리뷰 과정에서 변환 하는 과정이 들어갈 시 해당 API의 컨셉과 다른 부분(최적화)이 있어 배열의 포인터를 그대로 넘기는 형태로 디자인 되었습니다.

제가 이해한 바로는 말씀하신 IEnumerable을 사용하게 되면 MoveNext()후 current로 반환해야할 type과 point들을 반환할 또 다른 객체가 필요해질 것 같은데... 적절한 방법이 바로 떠오르지 않네요... 이 부분에 대해서는 좀 더 다른 분들과도 논의를 하도록 하겠습니다.

2021-08-17 00:08 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
우선 Array타입으로 선언된 인자를 IEnumerable로 변경하는것에 대해 오해가 있으신것 같습니다.

``` c#
public PathCommands(IEnumerable<PathCommandType> commands, IEnumerable<float> points)
```
1. 위와 같이 Parameter타입이 IEnumerable인 경우 당연히 Array도 인자로서 사용 가능합니다.
그래서 아래 예제 코드가 변경 없이 사용될 수 있습니다.
``` c#
PathCommands(new PathCommandType[] { 
  PathCommands.PathCommandType.MoveTo,
  PathCommands.PathCommandType.LineTo,
  PathCommands.PathCommandType.LineTo,
  PathCommands.PathCommandType.LineTo,
  PathCommands.PathCommandType.LineTo,
  PathCommands.PathCommandType.Close}, 
  new float[] {0.0f, -160.0f, 125.0f, 160.0f, -180.0f, -45.0f, 180.0f, -45.0f, -125.0f, 160.0f }
);
```
2. IEnumerable타입이더라도 Array일 수 있습니다. 
위에서 설명했듯이 Array타입은 IEnumerable타입입이므로 실제 입력된 Parameter가 Array라면 
 타입케스팅으로 Array타입으로 변환 가능합니다.
``` c#
public PathCommands(IEnumerable<PathCommandType> commands, IEnumerable<float> points) {
   PathCommandType[] commandsArray = null;
   if (commands is PathCommandType[] array) {
       commandsArray = array;
    }
```

3. API 사용자는 어차피 List를 사용할 수 밖에 없는 상황이 많습니다.
 API사용자는 path를 literal로 작성하지 않은 이상 파일로부터 path를 읽어오거나 다른 자료구조에서 변환하여 path를 작성하게 될것이며 이 상황에서는 정확한 path command의 갯수와 point의 개수를 알지 못하므로 어차피 사용자는 List자료형을 사용하여 path를 구축할 수 밖에 없고 API호출 전 최종적으로 `.ToArray() `같은 메소드로 변환하여 전달할 것입니다. 따라서 선언을 Array로 했다고 해서 변환 비용이 없어지는것이 아니고 그 변환이 API사용자에게 전환되었을뿐입니다.

4. `ToArray()`의 비용, 결국 Native API에 전달하기 위해서는 배열 타입으로 변환해야 하는데, 이 비용은 앞서 설명드린 Array to Array라면 사실상 0, List to array라면 TM1기준으로 100,000개의 Int타입 List를 Array변환하하는데 걸린 시간이 1ms 미만이였습니다. 이 비용이라면 무시 가능한 정도라고 생각됩니다.
(첫번째는 코드 JIT시간이 포함되어 있어서 다소 걸리는것처럼 보이나 두번째부터 원래의 속도대로 나옵니다)

그리고, CommandType과 Points를 한 자료구조로 묶고 이를 Native로 전달할때 다시 각각의 array로 변환하는 문제는 제가 느끼기에는 그런 변환에 들어가는 시간이, 앞서 Path정보를 파일로 부터 읽어오거나 다른 형태의 자료구조에서 변환하거나 하는데 걸리는 시간에 비교한다면 매우 작은 시간일것입니다. 최적화에 의미를 두고 해당 API를 추가하는것은 어느정도 이해는 되지만, 큰 차이는 없을것이라는 판단으로 API변경을 요청드려봅니다.

2021-08-19 09:09 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
상세한 설명 감사합니다. 말씀 주신 대로 진행하고 다시 리뷰 요청 드리겠습니다 :)

2021-08-19 09:10 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public enum PathCommandType
관련 패치 https://github.com/Samsung/TizenFX/pull/3435 merge 후에 함께 수정하도록 하겠습니다

2021-08-20 03:19 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public PathCommands(PathCommandType[] commands, uint commandCount, float[] points, uint pointCount)
IEnumerable을 사용하는 형태로 변경했습니다. 리뷰 감사합니다.

2021-08-20 03:20 UTC, JSUYA commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
> +        public enum PathCommandType
수정했습니다.

2021-08-20 04:43 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
> +            commands = pathCommands.Commands.ToArray();
else로 처리해야할것 같습니다.
```suggestion
            if (pathCommands.Commands is PathCommandType[] commandArray)
            {
                commands = commandArray;
            } 
            else 
            {            
                commands = pathCommands.Commands.ToArray();    
            }
```

2021-08-20 04:45 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
> +            Interop.Shape.AddPath(BaseHandle.getCPtr(this), commands, (uint)pathCommands.Commands.Count(), points, (uint)pathCommands.Points.Count());
이미 변환된 배열이 있고, C#의 배열 타입은 Length property가 있으므로 이걸 사용하는게 더 나을듯합니다.
```suggestion
            Interop.Shape.AddPath(BaseHandle.getCPtr(this), commands, (uint)commands.Length, points, (uint)points.Length);
```

2021-08-20 04:53 UTC, myroot approved these changes

2021-08-23 01:57 UTC, rabbitfor approved these changes
In your next commit, please change sample file name "CanvasViewSamsple.cs" to "CanvasViewSample.cs"

2021-08-23 02:01 UTC, rabbitfor commented
사용자가 입력한 형식이 올바르지 않을때 (command enum array가 요구하는 point 갯수와 입력된 point array 의 길이가 맞지 않을때) 아무일도 일어나지 않나요?

2021-08-23 03:07 UTC, JSUYA commented
> 사용자가 입력한 형식이 올바르지 않을때 (command enum array가 요구하는 point 갯수와 입력된 point array 의 길이가 맞지 않을때) 아무일도 일어나지 않나요?

잘못된 Path(깨진 이미지)가 출력됩니다.

2021-08-23 03:08 UTC, merged

2021-08-23 03:55 UTC, myroot commented
> 
> 
> > 사용자가 입력한 형식이 올바르지 않을때 (command enum array가 요구하는 point 갯수와 입력된 point array 의 길이가 맞지 않을때) 아무일도 일어나지 않나요?
> 
> 잘못된 Path(깨진 이미지)가 출력됩니다.


다음과 같은 상황에서 각각 어떻게 되는지...

1. PathCommand가 요구한 points보다 Points가 적을때
  a. points가 없는 Command는 무시된다
  b. point에 0, 0이 적용되어 Command가 실행된다.
  c. point에 알수 없는 값이 적용되어 Command가 실행된다.

2. PathCommand가 요구한 points보다 points가 많을때, 
   a. 요구 이상의 Points는 무시된다.

2021-08-23 05:41 UTC, JSUYA commented
> > > 사용자가 입력한 형식이 올바르지 않을때 (command enum array가 요구하는 point 갯수와 입력된 point array 의 길이가 맞지 않을때) 아무일도 일어나지 않나요?
> > (
> > 
> > 잘못된 Path(깨진 이미지)가 출력됩니다.
> 
> 다음과 같은 상황에서 각각 어떻게 되는지...
> 
> 1. PathCommand가 요구한 points보다 Points가 적을때
>    a. points가 없는 Command는 무시된다
>    b. point에 0, 0이 적용되어 Command가 실행된다.
>    c. point에 알수 없는 값이 적용되어 Command가 실행된다.
> 2. PathCommand가 요구한 points보다 points가 많을때,
>    a. 요구 이상의 Points는 무시된다.

안녕하세요 현재는 이렇게 동작 하고 있습니다.
(만약 1.c인데 1.b 처럼 동작하는거라면 버그라서 수정되어야 할것 같습니다.)
 1. PathCommand가 요구한 points보다 Points가 적을때
    b. point에 0, 0이 적용되어 Command가 실행된다.
 2. PathCommand가 요구한 points보다 points가 많을때,
    a. 요구 이상의 Points는 무시된다.