[NUI] Make Copy, Cut and Paste APIs public
Samsung/TizenFX pull request #3501
Opened 2021-09-05 13:37 UTC by shrouqsabah

Signed-off-by: Shrouq Sabah s.sabah@samsung.com
### Description of Change ###

Public open API list

- TextUtils.cs
    -  public static string CopyToClipboard(TextEditor textEditor) //API
    -  public static string CopyToClipboard(TextField textField) //API
    -  public static string CutToClipboard(TextEditor textEditor) //API
    -  public static string CutToClipboard(TextField textField) //API
    -  public static void PasteTo(TextEditor textEditor) //API
    -  public static void PasteTo(TextField textField) //API
 
- ACR:

2021-09-05 23:48 UTC, hyunjushin commented
Should we provide same method for each text input control?

2021-09-05 23:51 UTC, hyunjushin requested changes
please check if View type can be used as a parameter, because View is parent of TextEditor and TextField.

2021-09-07 03:57 UTC, dongsug-song commented on src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
> +        /// <since_tizen> 9 </since_tizen>
please remove this comment `// This will be public opened after ACR done. (Before ACR, need to be hidden as Inhouse API)`

2021-09-07 12:15 UTC, myroot commented
> please check if View type can be used as a parameter, because View is parent of TextEditor and TextField.


I think, View could not be use as parameter

2021-09-07 12:17 UTC, myroot commented on src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
> +        public static string CopyToClipboard(View textView)
Why change to View instead TextField, TextEditor?

2021-09-07 12:22 UTC, myroot requested changes
Please revert it `public static string CopyToClipboard(View textView)`

2021-09-07 13:18 UTC, myroot commented
> please check if View type can be used as a parameter, because View is parent of TextEditor and TextField.


It is failure of design, TextField and TextEditor should have common parent class. so many shareable API and codes are exitsed on the each class.

2021-09-07 15:04 UTC, shrouqsabah commented
> Please revert it `public static string CopyToClipboard(View textView)`

Done.

2021-09-07 23:20 UTC, hyunjushin approved these changes

2021-09-08 01:47 UTC, myroot commented
These APIs looks like a temporary and internal API, 

as I mentioned here, I hope that you guys do not make a temporal api as public
https://github.com/Samsung/TizenFX/pull/3398#issuecomment-895643918
https://github.com/Samsung/TizenFX/pull/3398#issuecomment-896546290
https://github.com/Samsung/TizenFX/pull/3398#issuecomment-897222788

2021-09-08 01:49 UTC, myroot commented
클립보드 API를 올바르게 디자인해서 오픈하시기를 바랍니다.
아직 native api 등의 구현 여건이 안된다면 현재의 API는 internal로만 공개하시기 바랍니다.

2021-09-08 01:57 UTC, myroot approved these changes

2021-09-13 03:27 UTC, merged