[NUI][ATSPI] set DefaultLinearItem role
Samsung/TizenFX pull request #3774
Opened 2021-11-26 03:27 UTC by kimcinoo

From this patch, it is able to set highlight to the DefaultLinearItem.

### Description of Change ###

### API Changes ###

 - ACR:

2021-11-26 06:17 UTC, everLEEst requested changes
looks better to move the feature into the super class for applying acc in all items.

2021-11-26 07:12 UTC, kimcinoo commented
> looks better to move the feature into the super class for applying acc in all items.

Moved lines to RecycleViewItem.

2021-12-06 07:38 UTC, everLEEst approved these changes
Looks good to me.
this OnInitialize method is virtual function,
so sub class might turn highlight off by overriding function! 
:+1:

2021-12-10 23:10 UTC, lol-github approved these changes
LGTM

2021-12-13 02:46 UTC, merged