[NUI] Add forward and backward direction type
Samsung/TizenFX pull request #3932
Opened 2022-02-09 02:58 UTC by JoogabYun

### Description of Change ###

[NUI] Add forward and backward direction type

### API Changes ###

 - ACR:

2022-02-14 01:24 UTC, Seoyeon2Kim approved these changes
LGTM!
The related dali patch is already merged, so NUI PR can be applied as well!
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-toolkit/+/270781/

2022-02-15 11:36 UTC, myroot requested changes
Please, write description of change with more details

https://google.github.io/eng-practices/review/developer/cl-descriptions.html

2022-02-18 00:48 UTC, kimcinoo approved these changes
No doubts!

2022-02-18 04:06 UTC, everLEEst approved these changes
Looks good to me

2022-02-21 01:07 UTC, JoogabYun commented
> https://google.github.io/eng-practices/review/developer/cl-descriptions.html

2022-02-21 01:10 UTC, JoogabYun commented
description 업데이트 했습니다. 리뷰 부탁드립니다.

2022-02-21 03:54 UTC, myroot commented
Forward / Backward가 새로 추가된 만큼
`ForawadFocusableView`, `BackwardFocusableView`도 추가되어야 하는것은 아닌가요?

Forward / Backward에 해당하는 View는 어떤 방식으로 지정되나요?

타 플랫폼의 경우 Tap index가 있어서, Tap index에 의해서 forward/backward가 결정되는데 NUI는 어떤 방식인지 궁굼합니다.

2022-02-21 04:30 UTC, JoogabYun commented
해당 패치는 tab, shift-tab에 대해 forward / backward 매핑시키는 패치입니다.
이를 통해 사용자가 View에서 GetNextFocusableView를 재정의하여 Forward/Backward를 처리할 수 있도록 한 패치입니다.
이에 해당 패치가 필요합니다.

플랫폼 내부에서의 동작은 아직 결정되지 않았습니다.
정책이 결정되는 대로 구현 및 그에 따른 ForawadFocusableView, BackwardFocusableView도 같이 추가될 것 같습니다.

2022-02-21 10:33 UTC, myroot approved these changes

2022-02-21 10:34 UTC, myroot commented
그냥 Type을 추가하면서 구현도 같이 하면 좋을것 같은데, 일단을 알겠습니다.

2022-02-22 04:43 UTC, merged