[NUI] Add an API for evaluating js with callback in WebView.
Samsung/TizenFX pull request #3943
Opened 2022-02-11 08:32 UTC by huayongxu

### Description of Change ###

### API Changes ###

 - ACR:

2022-02-14 02:38 UTC, dongsug-song commented
@huayongxu 
Thank you for your patch, but could you write description?
and could you upload this patch in API9 (for VD release) also?

2022-02-15 10:32 UTC, myroot requested changes
Please, write description of change

2022-02-16 01:17 UTC, huayongxu commented
> Please, write description of change

Done.

2022-02-16 03:42 UTC, myroot commented
> > Please, write description of change
> 
> Done.

as I think not enough, 

### Description of Change ###
Add EvaluateJavaScript method on WebView class

It evaluate javascript code with web engine and asynchronous returning result as string through callback.

##### how to use
``` c#
WebView webview = new WebView();
...
webview.EvaluateJavaScript("2+3", (result) => Console.WriteLine($"Eval : {result}"));
```

### API Changes ###
Add : 
``` c#
class WebView {
      public void EvaluateJavaScript(string script, JavaScriptMessageHandler handler)
}
```

2022-02-16 05:38 UTC, huayongxu commented
> @huayongxu Thank you for your patch, but could you write description? and could you upload this patch in API9 (for VD release) also?

Done.
The patch for API9 branch is https://github.com/Samsung/TizenFX/pull/3954

2022-02-16 05:38 UTC, huayongxu commented
> > > Please, write description of change
> > 
> > 
> > Done.
> 
> as I think not enough,
> 
> ### Description of Change
> Add EvaluateJavaScript method on WebView class
> 
> It evaluate javascript code with web engine and asynchronous returning result as string through callback.
> 
> ##### how to use
> ```cs
> WebView webview = new WebView();
> ...
> webview.EvaluateJavaScript("2+3", (result) => Console.WriteLine($"Eval : {result}"));
> ```
> 
> ### API Changes
> Add :
> 
> ```cs
> class WebView {
>       public void EvaluateJavaScript(string script, JavaScriptMessageHandler handler)
> }
> ```

Done

2022-03-10 06:58 UTC, myroot commented on src/Tizen.NUI/src/public/WebView/WebView.cs
> +            System.IntPtr ip = System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(handler);
Is this okay? You does not keep a handler from GC

2022-03-10 11:12 UTC, myroot approved these changes

2022-03-11 01:26 UTC, dongsug-song approved these changes
looks good to me

2022-03-11 01:26 UTC, merged