[NUI] set IsEnabled true as default behavior on ButtonStyle.
Samsung/TizenFX pull request #3947
Opened 2022-02-14 10:11 UTC by everLEEst

### Description of Change ###

Set IsEnabled state true on ButtonStyle.

Button class IsEnabled property is true by default but ButtonStyle isn't.
it can cause property value overwritten when user set custom stytle on button.

``` c#
var btn = new Button();
// Button.IsEnabled is true

var customBtnStyle = new ButtonStyle();
var customBtn = new Button(customBtnStyle);
// customBtn.IsEnabled is false 
```

to solve these problem,
we need to change default value on IsEnabled property of ButtonStyle.

### API Changes ###

 - ACR:

2022-02-15 10:32 UTC, myroot requested changes
Please, write description of change

2022-02-15 11:33 UTC, myroot commented
제가 알기로(듣기로) style에 nullable을 사용한 이유는 설정되지 않은 경우 기본값을 쓰도록 되어 있어서 그렇다고 들었습니다.
그러면, null인체로 두더라도 button의 IsEnabled의 기본값을 변경하지 않기 때문에 문제가 안되야 하는데, 이상합니다.

그리고 지금과 같이 Style의 IsEnabled를 true로 변경해버리면, 항상 Ture값으로 설정되어 버리기 때문에 View에서 의도적으로 IsEnabled를 fasle로 했을 경우에도 style이 적용되면서 IsEnabled가 true로 변경되는것 같습니다.(물론 Style이 생성자를 통해 먼저 설정되고 사용자가 설정하는 Property가 나중에 업데이트되기 때문에 실제로 문제가 되는 경우는 없지만, 의도적으로 style을 나중에 업데이트 하는 경우에는 문제가 될듯합니다. 물론 이 경우에는 IsEnabled뿐만 아니라 사용자가 입력했던 값과 다른 모든 Style에 명시된 값이 문제가 되긴 하지만요...)

2022-02-16 04:40 UTC, everLEEst commented
> 제가 알기로(듣기로) style에 nullable을 사용한 이유는 설정되지 않은 경우 기본값을 쓰도록 되어 있어서 그렇다고 들었습니다. 그러면, null인체로 두더라도 button의 IsEnabled의 기본값을 변경하지 않기 때문에 문제가 안되야 하는데, 이상합니다.
> 
> 그리고 지금과 같이 Style의 IsEnabled를 true로 변경해버리면, 항상 Ture값으로 설정되어 버리기 때문에 View에서 의도적으로 IsEnabled를 fasle로 했을 경우에도 style이 적용되면서 IsEnabled가 true로 변경되는것 같습니다.(물론 Style이 생성자를 통해 먼저 설정되고 사용자가 설정하는 Property가 나중에 업데이트되기 때문에 실제로 문제가 되는 경우는 없지만, 의도적으로 style을 나중에 업데이트 하는 경우에는 문제가 될듯합니다. 물론 이 경우에는 IsEnabled뿐만 아니라 사용자가 입력했던 값과 다른 모든 Style에 명시된 값이 문제가 되긴 하지만요...)

아 제가 히스토리를 모른 채 이슈 상황만 보고 바꾼 내용인데 말씀해주신 목적으로 nullable을 한 거라면 그 부분에서 잘못 처리되는게 없는지 먼저 확인해 보는게 좋겠네요. 알려주셔서 감사합니다!!

2022-03-28 04:53 UTC, dongsug-song commented
@everLEEst 
안녕하세요.
conflict 가 나고 있어서 확인 부탁드립니다.
혹시 다른 패치로 들어갔거나 해서 close 해도 되는 pr 이라면 close 부탁드립니다.
감사합니다.

2022-04-25 00:45 UTC, hyunjushin commented
@everLEEst   pending 되어 있는 PR로 보입니다. 확인 부탁드립니다.

2022-06-10 14:08 UTC, closed without merging