[NUI] Step move when scrollableBase failed to find next focusable view in visible area
Samsung/TizenFX pull request #4051
Opened 2022-03-21 07:11 UTC by everLEEst

This patch is on developing.
do not merge yet.

### Description of Change ###

### API Changes ###

 - ACR:

2022-03-21 07:56 UTC, myroot requested changes
스크롤 처리를 `GetNextFocusableView`에서 하는것은 올바르지 않은것 같습니다.
이 경우, 하위 클래스에서 override하기도 명확하지 않고, GetNextFocusableView 자체의 메소드 목적과도 맞지 않습니다. (SRP위반)

타 플랫롬의 경우, 

1. Key 이벤트 핸들러에서 children 간의 포커스 이동 처리
1-1. 1번에서 포커스 이동이 되었다면 event가 컨슘되어 더 이상 진핸 안됨
1-2. 1번에서 포커스 이동이 될 children가 없는 경우 event가 컨슘되지 않고 다음 step진행
2. 위 1단계에서 event가 consume이 안된 경우, 스크롤을 키 이벤트 방향에 맞춰 이동
2-1. 만약 해당 방향에 스크롤이 가능한 경우 event를 컨슘
2-1. 만약 해당 방향으로 스크롤이 불가능한 경우 event가 propagation

위와 같은 흐름으로 처리되는것 같습니다.

구조를 다시 생각해보셨으면 좋겠습니다.

2022-03-22 08:33 UTC, myroot commented
타 플랫폼의 정책을 찾아봐도 포커스 이동과 스크롤 이동 사이에서 어떤것이 우선위가 있고 어떻게 연계가 되는지 래퍼런스가 될만한 자료를 찾기가 어렵네요,
하지만 현 구현에서 이것만은 수정이 되었으면 합니다.

1. ScrollableBase내에서 포커스 이동이 가능한 Child View가 존재하는 경우 해당 View로 포커스 이동이 우선이 되었으면 좋겠습니다. 
   - 그 경우, 포커스가 이동한 View로 스크롤 또한 이동이 되기 때문에 전체적으로 자연스러운 동작이 될것 같습니다.
2. ScrollableBase내에서 포커스 이동이 가능한 Child View가 없는 경우에 스크롤이 되었으면 좋겠습니다.
3. 그리고 Scrollable내에 스크롤도 불가능한 상황에서는 key event컨슘이 안되었으면 좋겠습니다.
   - 그래야지, 상위 뷰로 이벤트가 전파되어 다른 View로 포커스가 이동이 자연스럽게 될것 같습니다.

그래서 아래와 같은 View tree 구조에서
[button0] ----- [scrollable  -- [button1] - [button2] - [button3(focused)] -------]
left 키 이벤트 발생
[button0] ----- [scrollable  -- [button1] - [button2(focused)] - [button3] -------]
left 키 이벤트 발생
[button0] ----- [scrollable  -- [button1(focused)] - [button2] - [button3] -------]
left 키 이벤트 발생
[button0] ----- [scrollable  ------ [button1(focused)] - [button2] - [button3] ---]
left 키 이벤트 발생
[button0] ----- [scrollable  ---------- [button1(focused)] - [button2] - [button3]]
(scrollabe의 ScrollX가 0인 상황에서) left 키 이벤트 발생
[button0(focused)] ----- [scrollable  ---------- [button1] - [button2] - [button3]]

와 같은 동작이 되었으면 합니다.

2022-03-23 08:20 UTC, everLEEst commented
>

2022-03-23 08:25 UTC, everLEEst commented
> 타 플랫폼의 정책을 찾아봐도 포커스 이동과 스크롤 이동 사이에서 어떤것이 우선위가 있고 어떻게 연계가 되는지 래퍼런스가 될만한 자료를 찾기가 어렵네요, 하지만 현 구현에서 이것만은 수정이 되었으면 합니다.
> 
> 1. ScrollableBase내에서 포커스 이동이 가능한 Child View가 존재하는 경우 해당 View로 포커스 이동이 우선이 되었으면 좋겠습니다.
>    
>    * 그 경우, 포커스가 이동한 View로 스크롤 또한 이동이 되기 때문에 전체적으로 자연스러운 동작이 될것 같습니다.
> 2. ScrollableBase내에서 포커스 이동이 가능한 Child View가 없는 경우에 스크롤이 되었으면 좋겠습니다.
> 3. 그리고 Scrollable내에 스크롤도 불가능한 상황에서는 key event컨슘이 안되었으면 좋겠습니다.
>    
>    * 그래야지, 상위 뷰로 이벤트가 전파되어 다른 View로 포커스가 이동이 자연스럽게 될것 같습니다.
> 
> 그래서 아래와 같은 View tree 구조에서 [button0] ----- [scrollable -- [button1] - [button2] - [button3(focused)] -------] left 키 이벤트 발생 [button0] ----- [scrollable -- [button1] - [button2(focused)] - [button3] -------] left 키 이벤트 발생 [button0] ----- [scrollable -- [button1(focused)] - [button2] - [button3] -------] left 키 이벤트 발생 [button0] ----- [scrollable ------ [button1(focused)] - [button2] - [button3] ---] left 키 이벤트 발생 [button0] ----- [scrollable ---------- [button1(focused)] - [button2] - [button3]] (scrollabe의 ScrollX가 0인 상황에서) left 키 이벤트 발생 [button0(focused)] ----- [scrollable ---------- [button1] - [button2] - [button3]]
> 
> 와 같은 동작이 되었으면 합니다.

안녕하세요. 우선 EFL에서의 동작 원리를 참조하여 아래와 같은 원칙을 기본으로 세웠습니다.
1. Focusable 한 Next Child가 탐색 범위(화면 + step 이동 거리)안에 있는 경우 -> 이동
2. Focusable 한 Next Child가 탐색 범위 밖에 있는 경우 ->  Step Move
3. Focusable 한 Next Child가 없는 경우 -> Step Move
단 SnapPage 시 Focusable 한 Next Child가 없는 경우 Page 단위로 Move
5. 각 양쪽 끝단에 도달시 Next Focusable Object로 이동

NUI의 GetNextFocusableView는 Control 내에서 포커서블한 객체를 찾기 위한 Override Method로 제공되고 있습니다. Null이 리턴될 경우 해당 컨트롤이 아닌 다른 컨트롤에서 Key를 컨슘하여 포커싱할 대상을 찾습니다.

2022-04-22 04:43 UTC, closed without merging