[MediaTool] Add new Ref/Unref APIs
Samsung/TizenFX pull request #4276
Opened 2022-05-20 06:56 UTC by hsgwon

### Description of Change ###

Add new reference counter based APIs - Ref()/Unref(). 
Ref() will make ref counter increase internally and Unref will make it decrease.
If ref counter changed to 0, MediaPacket instance will be disposed.

The behavior of existing Dispose() method is the same.

2022-05-21 14:10 UTC, myroot requested changes
Dispose시에 _handle을 초기화 하는 코드가 빠져 있고, ` GC.SuppressFinalize(this)` 또한 빠져 있어서 의도하지 않게 Unref 더 호출하는 상황이 발생합니다.

``` c#
   var packet = new MediaPacket( ... );
   packet.Dispose(); // 여기서 첫번째 Unref호출
   packet = null;
   GC.Collect(); // 여기서 GC에 의해서 소멸자가 불리고 두번째 Unref호출
```

Ref/Unref를 API로 노출해야할 이유를 잘 모르겠습니다. Ref와 Unref는 꼭 쌍으로 호출 해야 하는데, 이렇게 API로 추가됨으로서 쌍을 맞추지 않고 호출하는 위험에 노출시키는것 같습니다.

Ref/Unref를 사용해야만하는 시나리오는 제 생각으로는 없는것 같은데, 혹시 어떤 요구사항으로 Ref/Unref를 추가하셨는지 알려주시면 리뷰하는데 도움이 될것 같스빈다.

그리고, C#은 IDisposable인터페이스와 GC에 의한 소멸자 호출이 있기 때문에 Ref/Unref는 내부적으로 숨길수 있는 구현이 가능합니다 (https://stackoverflow.com/questions/9972763/implementing-raii-in-c-sharp)

2022-05-25 01:47 UTC, hsgwon commented
> Dispose시에 _handle을 초기화 하는 코드가 빠져 있고, ` GC.SuppressFinalize(this)` 또한 빠져 있어서 의도하지 않게 Unref 더 호출하는 상황이 발생합니다.
> 
> ```cs
>    var packet = new MediaPacket( ... );
>    packet.Dispose(); // 여기서 첫번째 Unref호출
>    packet = null;
>    GC.Collect(); // 여기서 GC에 의해서 소멸자가 불리고 두번째 Unref호출
> ```
> 
`_handle`과 `GC.SuppressFinalize(this)`는 Native.Unref()호출 시 내부적으로 호출되는 `DisposedCallback()`에서 수행됩니다.

> Ref/Unref를 API로 노출해야할 이유를 잘 모르겠습니다. Ref와 Unref는 꼭 쌍으로 호출 해야 하는데, 이렇게 API로 추가됨으로서 쌍을 맞추지 않고 호출하는 위험에 노출시키는것 같습니다.
> 
> Ref/Unref를 사용해야만하는 시나리오는 제 생각으로는 없는것 같은데, 혹시 어떤 요구사항으로 Ref/Unref를 추가하셨는지 알려주시면 리뷰하는데 도움이 될것 같습니다.
> 
> 저의 생각으로는 Ref가 필요한 상황에서는 MediaPacket객체를 생성하면 되고, Unref가 필요한 상황에서는 그렇게 생성한 MediaPacket를 dispose하면 될것 같습니다
> 
> * Ref를 대신할 MediaPacket객체 생성
> 
> ```cs
>  public MediaPacket(MediaPacket origin) : this(origin._handle)
>  {
>       Native.Ref(_handle);
>  }
> ```
> 
> 그리고, C#은 IDisposable인터페이스와 GC에 의한 소멸자 호출이 있기 때문에 Ref/Unref는 내부적으로 숨길수 있는 구현이 가능합니다 (https://stackoverflow.com/questions/9972763/implementing-raii-in-c-sharp)
생성된 MediaPacket을 여러 곳에서 받고 순서없이 

앱 단의 사용처가 여러 곳이고 사용을 완료하는 순서도 명확하지 않은 경우를 지원하기 위한 것입니다.
말씀하신 것처럼 Ref만 하고 Unref를 하지 않을 경우 leak이 발생할 수 있는 문제가 있었는데, 말씀하신 방법으로 하면 그런 문제는 없겠네요. 좀 더 고민해보겠습니다.

2022-05-26 00:10 UTC, myroot commented
>_handle과 GC.SuppressFinalize(this)는 Native.Unref()호출 시 내부적으로 호출되는 DisposedCallback()에서 수행됩니다.

제 생각으로는 그 부분이 제대로 동작하지 않는 상황이 발생합니다.
Ref / Unref를 C#레이어에서만 수행한다면 문제가 없지만, Ref/ Unref API가 native로부터 구현되어 있기에 Native영역에서도 Ref / Unref를 수행할 수 있다고 생각합니다. 

그래서 만약 Native영역에서 Ref로 래퍼런스 카운트를 올린 상태라면 문제가 됩니다. 
``` c#
   var packet = new MediaPacket( ... ); // Ref : 1
   SomeThingWithNative(); // 여기서 Native에서 packet의 Ref를 증가 , Ref : 2
   packet.Dispose(); // 여기서 첫번째 Unref호출, Ref : 1
   // Native에서 packet의 Ref를 증가시켰기 때문에, DisposedCallback 호출 안됨
   packet = null;
   GC.Collect(); // 여기서 GC에 의해서 소멸자가 불리고 두번째 Unref호출 되면서 객체가 삭제, Ref : 0 -> 객체 삭제
  // Native에서 packet을 사용하려고 했을때 crash 발생
```

2022-05-26 00:47 UTC, myroot commented
>앱 단의 사용처가 여러 곳이고 사용을 완료하는 순서도 명확하지 않은 경우를 지원하기 위한 것입니다.

기존 코드와 요구사항을 보면, callback안에서 획득한 packet은 callback이 종료되기 전에 Dispose하고 있는 상태인데, 
이 상황에서 event handler에서 packet의 lifetime을 늘리기 위한 요청인것 같습니다.

우선, IDisposable 인터페이스의 `Dispose()`의 명세는 지켜야한다고 생각됩니다. IDisposable인터페이스를 구현한 클래스는 Dispose메소드에서 unmanaged리소스를 정리해야 합니다. 즉 객체의 Dispose를 호출한 경우 더 이상 unmanaged리소스에 접근할 수 없도록 해야합니다. 또한 Dispose를 여러번 호출하더라도 unmanaged 리소스를 중복으로 해제해서도 안된다고 생각합니다.
심플하게 Dispose된 객체는 더 이상 사용할수 없어야 맞습니다.

이런 상황에서 packet의 lifetime을 늘리기 위해서는 위에 언급한대로 새로운 객체를 생성하는 방법이 가장 안전한 방법으로 보입니다.

2022-06-07 09:00 UTC, hsgwon commented
로컬 git branch에 문제가 생겨서 현 PR은 close하고 동일한 내용으로 다시 PR올리겠습니다.

2022-06-07 09:00 UTC, closed without merging