[NUI] Fix AlphaFunction delegate is GCed before native Animation is deleted
Samsung/TizenFX pull request #4382
Opened 2022-06-30 09:10 UTC by dongsug-song

### Description of Change ###
[NUI] Fix AlphaFunction delegate is GCed before native Animation is deleted
- Animation's user alpha function in c# is garbage collected, but in native DALi the Animation is still alive so it calls the user alpha function, this makes crash.
- keep the alpha function delegate's reference by adding it into List, and this List is also added into static Dictionary.
- https://github.sec.samsung.net/dotnet/NUIBackend/issues/162

### API Changes ###
none

2022-06-30 10:51 UTC, jaehyun0cho requested changes
@dongsug-song 님과 함께 코드를 살펴본 결과, static Dictionary에 Animation 핸들을 Add함으로 인해 Animation의 Dispose가 발생하지 않는 것을 확인하였습니다.
이 부분에 대한 수정이 필요해보입니다.

2022-06-30 11:58 UTC, myroot commented on src/Tizen.NUI/src/public/Animation/AlphaFunction.cs
> +        internal global::System.Delegate keepDelegate;
user가 정의한 delegate이기 때문에 userDelegate가 적당하지 않을까요?
object를 keep하기 위해서 추가한것이긴 하지만 keepDelegate는 해당 object를 잘 설명해주지 못하는것 같습니다.
```suggestion
        internal global::System.Delegate userDelegate;
```

2022-06-30 11:58 UTC, myroot commented on src/Tizen.NUI/src/public/Animation/Animation.cs
> +                }
AlphaFunction타입의 property의 setter이기 때문에 value가 null이 아닌 이상 AlphaFunction이 아닐수는 없습니다. 그래서 `is AlphaFunction`으로 검사하는것이 이상합니다.
```suggestion
                if (value != null)
                {
                    addAlphaFunctionInList(value);
                }
```

2022-06-30 12:15 UTC, myroot commented on src/Tizen.NUI/src/public/Animation/Animation.cs
> +            if (alpha?.keepDelegate != null)
지금까지는 Animation에 AnimateTo로 AlphaFunction을 전달하더라도 AlphaFunction객체가 Animation C#객체 내부에 저장이 안되어 있기 때문에 API사용자가 별도로 저장하고 있어야 했습니다. 그런데 이러한 구조가 일반적인 C#의 정책과는 맞지 않는 구조입니다.

이번에 이렇게 수정을 하는김에 user delegate를 사용하지 않는 AlphaFunction이더라도 저장해서 API사용자가 별도로 AlphaFunction을 유지하지 않더라도 되도록 하는게 어떨까요?

2022-07-01 11:35 UTC, myroot commented on src/Tizen.NUI/src/public/Animation/Animation.cs
> +            //Tizen.Log.Fatal("NUI", $"Dispose(type={type}) alpha Count={DisposeQueue.Instance.alphaList.Count}");
그런데 그 부분은 좀 이해가 안되는데, 그러면 근본적인 설계에 문제가 있는게 아닌가요? C#을 생각하지 않고 native로만 생각하더라도
user가 native로 정의한 callback (function)을 포함하여 animation객체를 삭제했는데, render thread에서는 삭제 여부와 상관 없이 호출을 해버리는건가요? 그 부분을 근본적으로 해결해야되지 않나요?

2022-07-04 04:56 UTC, jaehyun0cho commented on src/Tizen.NUI/src/public/Animation/Animation.cs
> +            //Tizen.Log.Fatal("NUI", $"Dispose(type={type}) alpha Count={DisposeQueue.Instance.alphaList.Count}");
아시는 것처럼 C# NUI에서는 AlphaFunction Delegate의 함수 포인터가 native쪽으로 전달되고 Delegate가 GC되어서 문제가 발생하게 되는데요.
제가 @heeyongsong 님으로부터 설명을 들은 바로는 native에서는 함수 포인터를 직접 사용하기 때문에 C# NUI와 동일한 문제는 발생하지 않게 됩니다. 
다만, 말씀해주신 것처럼 render thread에서 해당 callback 함수 포인터에 접근하여 이를 실행하기 때문에 이로 인한 문제가 발생할 수는 있을 것 같습니다. 따로 callback에 대한 lock 동기화 부분은 없는 것으로 보입니다.

2022-10-29 15:02 UTC, closed without merging