[NUI] Add DoActionExtension for LottieAnimationView
Samsung/TizenFX pull request #4446
Opened 2022-07-26 08:07 UTC by elishateng

### Description of Change ###

1. Add DoActionExtension for LottieAnimationView

### API Changes ###

 - ACR: None.

2022-07-28 03:47 UTC, zg2nets approved these changes
lgtm

2022-08-01 03:25 UTC, everLEEst requested changes

2022-08-01 03:25 UTC, everLEEst commented on src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
> +            FillColor,         ///< Fill color of the object, Type Property::VECTOR3
please check and resolve all warning messages.

2022-08-01 03:25 UTC, everLEEst commented on src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
> +        // This will be public opened after ACR done. (Before ACR, need to be hidden as Inhouse API)
please add summary.

2022-08-01 03:25 UTC, everLEEst commented on src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
> +        // This will be public opened after ACR done. (Before ACR, need to be hidden as Inhouse API)
please add summary.

2022-08-01 03:25 UTC, everLEEst commented on src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
> +
same here.

2022-08-01 03:25 UTC, everLEEst commented on src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
> +
here also.

2022-08-24 09:29 UTC, dongsug-song commented
@elishateng 
Hello, 
Thank you for your work.
but this functionality has been added by the following patches, so the PR is not needed currently.

https://github.com/Samsung/TizenFX/pull/4467
https://review.tizen.org/gerrit/#/c/platform/core/uifw/dali-csharp-binder/+/279320/

so I am just closing this PR.
I am sorry to close your PR without your agreeing, but please understand the situation and not be confused.
thank you.

2022-08-24 09:29 UTC, closed without merging