[NUI] Support window move event
Samsung/TizenFX pull request #4468
Opened 2022-08-08 01:30 UTC by sparrow74

Add window move event.
This event occurs when

2022-08-10 06:26 UTC, dongsug-song approved these changes
approved.

but please add sample code or test case from next time.
and please resolve the warnings from next time such as this =>

**_src/Tizen.NUI/src/public/Window/WindowEvent.cs#L1265
Do not nest type MovedEventArgs. Alternatively, change its accessibility so that it is not externally visible._**

2022-08-16 06:52 UTC, everLEEst requested changes

2022-08-16 06:52 UTC, everLEEst commented on src/Tizen.NUI/src/internal/Interop/Interop.WindowMovedSignal.cs
> + * Copyright(c) 2021 Samsung Electronics Co., Ltd.
```suggestion
 * Copyright(c) 2022 Samsung Electronics Co., Ltd.
```

2022-08-16 06:52 UTC, everLEEst commented on src/Tizen.NUI/src/internal/Window/WindowMovedSignal.cs
> + * Copyright(c) 2021 Samsung Electronics Co., Ltd.
```suggestion
 * Copyright(c) 2022 Samsung Electronics Co., Ltd.
```

2022-08-18 13:55 UTC, myroot commented on src/Tizen.NUI/src/public/Window/WindowEvent.cs
> +            }
```suggestion
            movedHandler?.Invoke(this, new MovedEventArgs {
                 WindowPosition = this.WindowPosition
            });
```

2022-08-19 09:33 UTC, everLEEst commented on src/Tizen.NUI/src/public/Window/WindowEvent.cs
> +            }
생각해보지 못했던 Null Exception 케이스인데 좋은 공부 됐습니다. 감사합니다.

2022-10-29 15:02 UTC, closed without merging