Add DrawableView
Samsung/TizenFX pull request #4491
Opened 2022-08-17 06:58 UTC by dkdk-ryu

### Description of Change ###

### API Changes ###

 - ACR:

2022-08-19 09:27 UTC, everLEEst requested changes

2022-08-19 09:27 UTC, everLEEst commented on src/Tizen.NUI/src/public/BaseComponents/DrawableView.cs
> +        {
could you please check the above warnings?
if you think this message can be ignored,
you can suppress them by using
```c#
 [global::System.Diagnostics.CodeAnalysis.SuppressMessage(ReasonType, Descriptions)]
```

2022-08-19 09:27 UTC, everLEEst commented on src/Tizen.NUI/src/public/BaseComponents/DrawableView.cs
> +
please check all field messages.
you can use the Property for public.

2022-08-24 09:13 UTC, dongsug-song commented
@dkdk-ryu 
Hello, 
I'm sorry for the inconvenience.
Some patches has been merged only into the master branch, so the master branch and the DevelNUI branch were conflicted.
So I did hard reset the DevelNUI branch.
Could you rebase the patch and resolve the conflict?
thank you.

the following tip could be helpful :
(execute from the work branch)
1) git fetch upstream
2) git rebase --onto=upstream/DevelNUI HEAD~1
3) git push -f
(number of commits on the work branch has to be given after '~', for this case it is 1)

2022-11-01 15:02 UTC, closed without merging