Add buttons
Samsung/TizenFX pull request #4530
Opened 2022-08-30 10:51 UTC by jaehyun0cho

### Description of Change ###

### API Changes ###

 - ACR:

2022-08-30 10:52 UTC, jaehyun0cho commented
This PR should be merged with Rebase and merge.

2022-08-30 10:59 UTC, dongsug-song commented
@jaehyun0cho 
thank you for the patch. could you explain why these components are needed?
could you update it in description?
thank you.

2022-08-30 11:07 UTC, jaehyun0cho commented
> @jaehyun0cho thank you for the patch. could you explain why these components are needed? could you update it in description? thank you.

Thank you for your comment.
Tizen 7.0 UX introduces OutlinedButton and TextButton.

2022-08-30 11:52 UTC, everLEEst requested changes
We don't need OutlineButton, TextButton class for this.
adding style in the default theme is enough.

2022-08-30 11:56 UTC, jaehyun0cho commented
> We don't need OutlineButton, TextButton class for this. adding styles in the default theme are enough.

Thank you for your comment.
I have removed OutlinedButton and TextButton classes.
Instead, I have modified the samples to use "Tizen.NUI.Components.OutlinedButton" and "Tizen.NUI.Components.TextButton" styles.

2022-08-30 12:00 UTC, everLEEst approved these changes
Overall looks good to me.
but before pushing this patch, I think we need to decide naming policy of styles.
I think we have two good solutions.
```c#
Tizen.NUI.Components.Button
Tizen.NUI.Components.OutlinedButton
Tizen.NUI.Components.TextButton
```
or
```
Tizen.NUI.Components.Button  (.Default)
Tizen.NUI.Components.Button.Outlined
Tizen.NUI.Components.Button.TextOnly //Text might quite confusing in this case.
```

2022-08-30 12:14 UTC, jaehyun0cho commented
> Overall looks good to me. but before pushing this patch, I think we need to decide naming policy of styles. I think we have two good solutions.
> 
> ```cs
> Tizen.NUI.Components.Button
> Tizen.NUI.Components.OutlinedButton
> Tizen.NUI.Components.TextButton
> ```
> 
> or
> 
> ```
> Tizen.NUI.Components.Button  (.Default)
> Tizen.NUI.Components.Button.Outlined
> Tizen.NUI.Components.Button.TextOnly //Text might quite confusing in this case.
> ```

Good point!
I prefer the second way.
Reviewers, please leave your opinions~

2022-09-01 01:18 UTC, jaehyun0cho commented
I have updated this PR to use the style naming rule as follows.
"Tizen.NUI.Components.Button.Outlined"
"Tizen.NUI.Components.Button.TextOnly"

2022-09-01 02:53 UTC, dongsug-song approved these changes
very good idea~
we can avoid to create new classes which seem to be heavy and rich.

2022-09-01 04:34 UTC, merged