Mark all Tizen.Security.PrivacyPrivilegeManager APIs as deprecated
Samsung/TizenFX pull request #4934
Opened 2023-01-26 15:23 UTC by dmichaluk

Change-Id: I519abb343b5f4e49d2256a9b0abf69d4fb755632

### Description of Change ###
Mark all Tizen.Security.PrivacyPrivilegeManager APIs as deprecated

2023-01-27 05:33 UTC, shyunMin commented
Looks good to me.

2023-02-02 08:06 UTC, wiertel requested changes

2023-02-02 08:06 UTC, wiertel commented on src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PrivacyPrivilegeManager.cs
> +    [Obsolete("Deprecated in API11, Will be removed in API13. This API will be removed without any alternatives.")]
I see a comma before capitalized word. Please change "API11, Will" -> "API11. Will" OR "API11, will"

2023-02-02 12:41 UTC, dmichaluk commented on src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PrivacyPrivilegeManager.cs
> +    [Obsolete("Deprecated in API11, Will be removed in API13. This API will be removed without any alternatives.")]
Done.

2023-03-03 10:58 UTC, wiertel approved these changes

2023-05-04 08:05 UTC, dmichaluk commented
@wiertel Can you merge this PR?

2023-05-08 10:15 UTC, dmichaluk commented
@myroot Can you merge this PR?

2023-05-08 10:18 UTC, wiertel approved these changes

2023-05-08 10:22 UTC, myroot commented
> @myroot Can you merge this PR?

In general, merge directly from TG.
I'll do it if you don't have permission.

2023-05-08 10:26 UTC, dmichaluk commented
@myroot I don't have permission, "Only those with write access to this repository can merge pull requests."

2023-05-08 10:26 UTC, merged