[NUI] Add Comment on the View.VisibilityChanged event
Samsung/TizenFX pull request #5286
Opened 2023-05-18 06:55 UTC by bshsqa

### Description of Change ###

### API Changes ###

 - ACR:

2023-05-18 07:05 UTC, hinohie approved these changes

2023-05-18 07:09 UTC, Seoyeon2Kim commented on src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
> +        /// If VisibilityChangedEventArgs.Type is SELF, then VisibilityChangedEventArgs.Visibility is true if this View's Visibility property is true.
This sentence is a little awkward, especially on the grammar.
-> If A, B if C.
You mean, 
```suggestion
        /// If VisibilityChangedEventArgs.Type is SELF and  this View's Visibility property is true, then VisibilityChangedEventArgs.Visibility is true.
```
Is it what you want to explained?

2023-05-18 07:13 UTC, Seoyeon2Kim commented on src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
> +        /// For reference, a view is only shown if it and it's parents (up to the root view) are also visible, are not transparent, and this view has a non-zero size.
```suggestion
        /// For reference, a view is only shown if the view and its parents (up to the root view) are also visible, they are not transparent, and the view has a non-zero size.
```

2023-05-18 07:13 UTC, Seoyeon2Kim requested changes
And please update the description of this PR

2023-05-22 01:22 UTC, dongsug-song approved these changes
approved

2023-05-22 04:53 UTC, Seoyeon2Kim approved these changes

2023-05-25 04:33 UTC, merged