Particle System for NUI
Samsung/TizenFX pull request #5449
Opened 2023-08-03 14:42 UTC by jsr184

### Description of Change ###
Implementation of the Particle System for NUI (binding to the native side + C# specific implementation of certain elements).

Classes included:
Tizen.NUI.ParticleSystem.ParticleEmitter
Tizen.NUI.ParticleSystem.ParticleSource<T>
Tizen.NUI.ParticleSystem.ParticleSourceInterface
Tizen.NUI.ParticleSystem.ParticleModifier<T>
Tizen.NUI.ParticleSystem.ParticleModifierInterface
Tizen.NUI.ParticleSystem.Particle

ParticleSource and ParticleModifier invoke callbacks on the update thread so the implementation of those callbacks should not be accessing NUI objects.

2023-08-04 14:34 UTC, adeelkazmi approved these changes

2023-08-04 14:37 UTC, adeelkazmi requested changes
There are 5 commits in this change including temporary ones. Please merge into 1.

2023-08-04 15:32 UTC, adeelkazmi approved these changes

2023-08-05 06:57 UTC, hinohie commented on src/Tizen.NUI/src/public/ParticleSystem/ParticleEmitter.cs
> +    public enum ParticleBlendingMode
```suggestion
    [EditorBrowsable(EditorBrowsableState.Never)]
    public enum ParticleBlendingMode
```

We should also mark public enums as 'hidden' if we are not prepare to ACR.

2023-08-05 06:57 UTC, hinohie commented on src/Tizen.NUI/src/public/ParticleSystem/ParticleEmitter.cs
> +    public class ParticleEmitter : BaseHandle
```suggestion
    [EditorBrowsable(EditorBrowsableState.Never)]
    public class ParticleEmitter : BaseHandle
```

Please make this class as hidden, if you don't prepare ACR.

2023-08-07 13:33 UTC, hinohie commented
It is just our NUI team's usual process but...

Usually  ACR process spend more than 3~4 month.
So, We make Implement PR with internal-hidden only APIs first.
And after that PR merged, make new PR only for ACR.

https://github.com/Samsung/TizenFX/pull/5452/files

Please check what I'm doimg now. and also please make some API as hidden, what I write comment to you

2023-08-08 04:06 UTC, dongsug-song commented
@jsr184 
Hello, 
as Mr. hinohie explained above, please add `[EditorBrowsable(EditorBrowsableState.Never)]` on every API to make them hidden APIs. and to release them in public, you need to procede ACR. 
please check again. 
thank you.

2023-09-12 00:13 UTC, hinohie commented
PR #5548 is more latest version. We will close this PR.

2023-09-12 00:13 UTC, closed without merging