[NUI] Fix some SVACE issues.
Samsung/TizenFX pull request #5759
Opened 2023-11-17 08:48 UTC by zhouhao02

Value args.OldItems, which is result of method invocation with possible null return value, is dereferenced in member access expression args.OldItems.Count

### Description of Change ###

### API Changes ###

 - ACR:

2023-11-17 08:57 UTC, xiaowei-guan approved these changes
LGTM

2023-11-17 08:58 UTC, huayongxu approved these changes
lgtm

2023-11-17 09:01 UTC, elishateng approved these changes
LGTM

2023-11-17 09:01 UTC, elishateng commented on src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableGroupedSource.cs
> +            if(newitems==null || oldItems == null)
(newitems == null ...)

2023-11-17 09:02 UTC, zg2nets commented on src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableGroupedSource.cs
> +            if(newitems==null || oldItems == null)
Keep the format consistent

2023-11-17 09:02 UTC, zg2nets requested changes

2023-11-17 09:02 UTC, zg2nets commented on src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableGroupedSource.cs
> +            int groupCount = newitems.Count;
Keep the format consistent

2023-11-20 05:53 UTC, dongsug-song approved these changes
approved

2023-11-20 05:53 UTC, merged

2024-01-24 06:49 UTC, wanchao-xu reviewed
Looks good to me

2024-04-12 07:00 UTC, AdunFang reviewed
It is OK.